'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {Heart,LogOut,Package,PawPrint,Save,UserRound} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
import type {User} from '@supabase/supabase-js';

type Pet={id?:string;name:string;type:'Собака'|'Кіт';age:string;weight:string;breed:string;notes:string};

export default function AccountPage(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[saved,setSaved]=useState('');
 const [pet,setPet]=useState<Pet>({name:'',type:'Собака',age:'',weight:'',breed:'',notes:''});
 useEffect(()=>{const supabase=createClient();if(!supabase){setLoading(false);return}supabase.auth.getUser().then(async({data})=>{const u=data.user||null;setUser(u);if(u){const {data:p}=await supabase.from('pets').select('id,name,type,age,weight,breed,notes').eq('user_id',u.id).limit(1).maybeSingle();if(p)setPet(p as Pet)}setLoading(false)})},[]);
 async function savePet(e:FormEvent){e.preventDefault();setSaved('');const supabase=createClient();if(!supabase||!user)return;const payload={user_id:user.id,name:pet.name,type:pet.type,age:pet.age,weight:pet.weight,breed:pet.breed,notes:pet.notes};const q=pet.id?supabase.from('pets').update(payload).eq('id',pet.id):supabase.from('pets').insert(payload).select().single();const {data,error}=await q;if(data&&'id'in data)setPet({...pet,id:String(data.id)});setSaved(error?'Не вдалося зберегти':'Збережено') }
 async function signOut(){const supabase=createClient();if(supabase)await supabase.auth.signOut();location.href='/'}
 if(loading)return <main className="wrap page"><div className="empty">Завантажуємо профіль…</div></main>;
 if(!user)return <main className="wrap page narrow"><div className="accountEmpty"><div className="accountIcon"><UserRound/></div><h1>Профіль LAPKA</h1><p>Увійди або створи акаунт, щоб зберігати замовлення й профіль улюбленця.</p><div className="heroBtns"><Link className="primary" href="/sign-in">Увійти</Link><Link className="secondary" href="/sign-up">Створити акаунт</Link></div></div></main>;
 const name=user.user_metadata?.full_name||'Привіт';
 return <main className="wrap page accountPage"><div className="accountTop"><div><span className="eyebrow">Мій акаунт</span><h1>{name}</h1><p>{user.email}</p></div><button className="secondary buttonLike" onClick={signOut}><LogOut size={17}/>Вийти</button></div><div className="accountQuick"><Link href="/orders"><Package/><div><b>Замовлення</b><small>Історія покупок</small></div></Link><Link href="/catalog?favorites=1"><Heart/><div><b>Обране</b><small>Збережені товари</small></div></Link><a href="#pet"><PawPrint/><div><b>Улюбленець</b><small>Підбір товарів</small></div></a></div><section id="pet" className="accountSection"><div className="accountSectionCopy"><span className="sectionLabel">Профіль улюбленця</span><h2>Підбір без зайвого.</h2><p>Вкажи базові дані — магазин зможе приховувати невідповідні товари й точніше радити потрібне.</p></div><form className="card modernForm petAccountForm" onSubmit={savePet}><div className="segmented modernSegmented"><button type="button" className={pet.type==='Собака'?'sel':''} onClick={()=>setPet({...pet,type:'Собака'})}>Собака</button><button type="button" className={pet.type==='Кіт'?'sel':''} onClick={()=>setPet({...pet,type:'Кіт'})}>Кіт</button></div><label>Ім’я<input value={pet.name} onChange={e=>setPet({...pet,name:e.target.value})} required placeholder="Бейлі"/></label><div className="two"><label>Вік<input value={pet.age} onChange={e=>setPet({...pet,age:e.target.value})} placeholder="6 місяців"/></label><label>Вага<input value={pet.weight} onChange={e=>setPet({...pet,weight:e.target.value})} placeholder="11 кг"/></label></div><label>Порода або розмір<input value={pet.breed} onChange={e=>setPet({...pet,breed:e.target.value})} placeholder="Метис, середня порода"/></label><label>Особливості<textarea value={pet.notes} onChange={e=>setPet({...pet,notes:e.target.value})} placeholder="Улюблені смаки, чутливість, важливі деталі"/></label><div className="saveRow"><button className="primary" type="submit"><Save size={17}/>Зберегти</button>{saved&&<span className="savedText">{saved}</span>}</div></form></section></main>
}
